dist: focal
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=swe1_app,polls manage.py test

after_script:
  - coveralls  

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"  
  app: "swe1_app_beanstalk"  
  env: "swe1-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-730335518224"
  on:
    repo: jwb10028/swe1_app
    branch: main
  skip_cleanup: true  