language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt  # Install dependencies
  - pip install flake8 black coverage coveralls  # Install code quality tools

before_script:
  - black --check .  
  - flake8 .  

script:
  - python manage.py migrate  
  - coverage run manage.py test  

after_success:
  - coveralls  

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"  
  app: "django-tut"  
  env: "django-environment" 
  on:
    branch: main  
