language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt  # Install dependencies
  - python -m pip install --upgrade pip setuptools wheel

script:
  - python manage.py migrate  
  - coverage run --source=swe1_app manage.py test

after_success:
  - coveralls  

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"  
  app: "django-tut"  
  env: "django-environment" 
  on:
    branch: main  