dist: focal
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt  # Install dependencies

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - coverage run --source=swe1_app,polls manage.py test

after_success:
  - coveralls  

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"  
  app: "swe1_app_beanstalk"  
  env: "swe1-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-730335518224"
  on:
    branch: main
  skip_cleanup: true  