language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt  # Install dependencies
  - python -m pip install --upgrade pip setuptools wheel

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - coverage run --source=swe1_app manage.py test

after_success:
  - coveralls  

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"  
  app: "django-tut"  
  env: "django-environment"
  bucket_name: "elasticbeanstalk-us-west-2-730335518224"
  bucket_path: "django-tutorial" 
  on:
    branch: main  